# Generated by Django 4.2.6 on 2023-10-16 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=225)),
                ("ownerId", models.BigIntegerField()),
                ("creationDate", models.DateField(verbose_name=datetime.datetime.now)),
                ("groupCatigory", models.CharField(max_length=225, null="misc")),
                ("coverImg", models.ImageField(default=None, upload_to="images/")),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="group",
            field=models.CharField(max_length=225, null="misc"),
            preserve_default="misc",
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(verbose_name=datetime.datetime.now),
        ),
    ]
