# Generated by Django 4.2.6 on 2023-10-19 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_delete_group"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="group",
            new_name="eventType",
        ),
    ]
