# Generated by Django 4.2.6 on 2023-10-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_group_event_group_alter_event_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="coverImg",
            field=models.ImageField(default=None, upload_to="images/"),
        ),
    ]
