# Generated by Django 4.2.6 on 2023-10-28 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0001_initial"),
        ("events", "0002_user2event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="eventGroup",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="groups.group",
            ),
        ),
    ]
