# Generated by Django 4.2.6 on 2023-10-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_event_coverimg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="coverImg",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="images/"
            ),
        ),
    ]
