# Generated by Django 4.2.6 on 2023-10-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_alter_event_coverimg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="coverImg",
            field=models.CharField(default="test.png", max_length=225),
        ),
    ]
