# Generated by Django 4.2.6 on 2023-10-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_profilepic"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="firstName",
            field=models.CharField(default="John", max_length=225),
        ),
        migrations.AddField(
            model_name="user",
            name="lastName",
            field=models.CharField(default="Doe", max_length=225),
        ),
    ]
