# Generated by Django 4.2.6 on 2023-10-22 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_group_description_group_events_user_blocked_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="blocked",
        ),
        migrations.RemoveField(
            model_name="user",
            name="followers",
        ),
        migrations.RemoveField(
            model_name="user",
            name="following",
        ),
        migrations.AlterField(
            model_name="user",
            name="profilePic",
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.CreateModel(
            name="UserRelationships",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isBlocked", models.BooleanField()),
                ("isFollowed", models.BooleanField()),
                (
                    "firstUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "secondUser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
